# NumPy 教程


## 1. 简介

NumPy 是在 Python 中进行科学计算经常用到的基本包，主要用于对多维数组执行计算，有着广泛的应用场景，例如：

- **机器学习：** 在机器学习中，经常需要进行各种矩阵运算，NumPy 提供了编写简单、运行快速的运算接口。此外，NumPy 数组也被用于存储训练数据和模型的参数。
- **图像处理：** 计算机中的图像被表示为多维数组。
- **数学任务：** 替代 MatLab 执行例如数值积分、微分、内插、外推等数学任务。

要使用 NumPy，需要首先导入 `numpy` 库：

In [2]:
import numpy as np

`ndarray` 是 NumPy 中的基本对象，它是一个由相同类型的元素组成的多维数组，通过非负整数元组进行索引。在 NumPy，每个维度被称为轴 (`axis`) 。下面我们将围绕 `ndarray` 的基本操作，展开本次教程。

## 2. 数组的创建

详细文档请参见 [Array creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)。

### 2.1 从 python 的序列容器创建数组

我们可以直接使用 [`np.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html) 从 python 的 list 或 tuple 创建数组，例如：

In [3]:
arr_1d = np.array((1, 2, 3))
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
print(arr_1d)

[1 2 3]


In [5]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


数组有以下常用的属性：

In [6]:
print('维度（也称 rank）：', arr_2d.ndim)
print('形状：', arr_2d.shape)
print('元素总数：', arr_2d.size)
print('元素数据类型：', arr_2d.dtype)

维度（也称 rank）： 2
形状： (2, 3)
元素总数： 6
元素数据类型： int32


### 2.2 使用 NumPy 预置的函数创建数组

NumPy 预置了很多按特定规则创建数组的函数，下面介绍一些常用的函数。

#### 2.2.1 一维数组创建函数

常用的一维数组创建函数包括：
- [`arange([start, ]stop, [step, ])`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html): 类似于 python 中的 `range`，创建以 `start` 起（含）至 `stop`（不含），步长为 `step` 的数组。
- [`linspace(start, stop, num=50, endpoint=True)`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html): 创建从 `start` 开始（含）至 `stop` （是否包含取决于 `endpoint`），由 `num` 个均匀散布的元素组成的数组。
- [`logspace(start, stop, num=50, endpoint=True, base=10.0)`](https://numpy.org/doc/stable/reference/generated/numpy.logspace.html): 创建从 `base ** start` 开始（含）至 `base ** stop` 结束（是否包含取决于 `endpoint`），由 `num` 个在对数尺度上均匀散布的元素组成的数组。

In [7]:
import numpy as np  
  
arr = np.arange(10, 0, -2)  
print(arr)  # 输出: [10 8 6 4 2]

[10  8  6  4  2]


In [27]:
print(np.arange(3,dtype=float))  # 输出: [0. 1. 2.]
print(np.arange(1, 7, 2))
print(np.linspace(0, 40, 5))
print(np.linspace(0, 50, 5, endpoint=True))
print(np.logspace(0, 3, 4))

[0. 1. 2.]
[1 3 5]
[ 0. 10. 20. 30. 40.]
[ 0.  12.5 25.  37.5 50. ]
[   1.   10.  100. 1000.]


#### 2.2.2 二维数组创建函数

常用的二维数组创建函数包括：
- [`eye(N, M=None)`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html): 创建 $N \times M$ 的单位矩阵。
- [`diag(v)`](https://numpy.org/doc/stable/reference/generated/numpy.diag.html): 创建以 `v` 为对角线元素的对角矩阵。

In [14]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
print(np.diag([1, 2, 3]))
print(np.diag((1,2,3)))
print(np.diag(range(1,3,1)))


[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0]
 [0 2]]


#### 2.2.3 通用数组创建函数

该类函数在创建数组时，通常需要指定数组的形状，或者给定一个参考数组。常见的通用数组创建函数包括：
- [`zeros(shape)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html): 创建一个形状为 `shape` 的零矩阵。
- [`zeros_like(arr)`](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html): 创建一个形状与 `arr` 相同的零矩阵。
- [`ones(shape)`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html): 创建一个形状为 `shape` 的全 1 矩阵。
- [`ones_like(arr)`](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html): 创建一个形状与 `arr` 相同的全 1 矩阵。
- [`random.random(shape)`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html): 创建一个形状为 `shape`，元素在 $[0, 1)$ 随机取值的矩阵。

In [16]:
arr_zero = np.zeros((2, 3))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones_like(arr_zero)
np.ones(1,dtype=int)

array([1])

In [30]:
print(np.random.random((2, 2)))

[[0.16809034 0.9084705 ]
 [0.2535411  0.6176984 ]]


### 注

NumPy 创建数组的函数一般还可接受名为 `dtype` 的参数，用于指定元素的数据类型。可选的类型可以参见此[链接](https://www.numpy.org.cn/user/basics/types.html)。例如：

In [29]:
print(np.zeros((1,), dtype=int))
print(np.zeros((1,), dtype=np.float32))
print(np.arange(1,3))

[0]
[0.]
[1 2]


## 3. 数组的索引

详细文档请参见 [Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html)。

### 3.1 切片

我们可以采用类似 python 中的 list 的方式对 ndarray 数组进行切片。但不同的是，ndarray 可以以逗号分隔，一次性指定每个维度的切片方式。

![](assets/numpy_2D_slicing_diagram-1.jpg)

In [31]:
arr = np.arange(11, 36).reshape((5, 5))  # `reshape` 可以改变数组形状，详见后续章节
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
print(arr[0, 1:4])  # 注意维度变化，原来的第 0 维被压缩了
print(arr[1:4, 0])  # 注意维度变化，原来的第 1 维被压缩了
print(arr[::2, ::2])  # 指定步长
print(arr[:, 1])  # 第 0 维全选

注意！通过切片选择返回的数组是原始数组的一个视图 (view)，并未发生数据的拷贝。在视图上做的修改都会反馈到原始数组上。比如：

In [32]:
arr = np.arange(1, 7).reshape((2, 3))
print(arr)
view = arr[:, 1]
print(view)
view[0] = 9
print(arr)

[[1 2 3]
 [4 5 6]]
[2 5]
[[1 9 3]
 [4 5 6]]


如何避免呢？使用 [`ndarray.copy`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html) 或 [`copy`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html) 完成对数组数据的深拷贝。

In [33]:
view = arr[:, 1].copy()
view[0] = 7
print(arr)

[[1 9 3]
 [4 5 6]]


### 3.2 整数数组索引

我们可以使用整数数组进行索引。通过为每一个维度提供一个坐标数组，可以选取任意位置的元素。此时返回的数组不再是一个 view 了。

In [42]:
arr = np.arange(1, 7).reshape((2, 3))
print(arr)

# An example of integer array indexing.
# The returned array will have shape (3,)
print(arr[[0, 1, 0], [0, 1, 2]])
print(type(arr[[0, 1, 0], [0, 1, 2]]))
# The above example of integer array indexing is equivalent to this:
print(np.array([arr[0, 0], arr[1, 1], arr[0, 2]]))
print(np.array(arr[[0,1,0],[0,1,2]]))

copy_arr = arr[[0, 1, 0], [0, 1, 2]]
print(copy_arr)
copy_arr[0] = 9
print("\n",arr)

[[1 2 3]
 [4 5 6]]
[1 5 3]
<class 'numpy.ndarray'>
[1 5 3]
[1 5 3]
[1 5 3]

 [[1 2 3]
 [4 5 6]]


### 3.3 布尔数组索引

我们可以使用一个与原数组形状匹配的布尔数组来选择元素（此时返回的数组同样不再是一个 view 了）。例如：

In [43]:
mask = (arr % 2 == 0)  # 选择偶数
print(mask)
print(arr[mask])

[[False  True False]
 [ True False  True]]
[2 4 6]


## 4. 数组的运算

### 4.1 算术运算

NumPy 中 `ndarray` 数组的基本运算（加、减、乘、除、整除、求余、幂等）都是逐元素 (element-wise) 的（例如这里的乘法并不是矩阵乘法）。其指定方式既可以采用 `+`, `-`, `*`, `/`, `//`, `%`, `**` 等运算符，也可以使用 NumPy 函数。

In [44]:
x = np.array([[1,2],[3,4]], dtype=np.float32)
y = np.array([[5,6],[7,8]], dtype=np.float32)

print('Elementwise sum:')
print(x + y)  # np.add(x, y)

print('Elementwise product:')
print(x * y)  # np.multiply(x, y)

print('Elementwise division:')
print(x / y)  # np.divide(x, y)

print('Elementwise power:')
print(x ** 2)  # np.power(x, 2)

Elementwise sum:
[[ 6.  8.]
 [10. 12.]]
Elementwise product:
[[ 5. 12.]
 [21. 32.]]
Elementwise division:
[[0.2        0.33333334]
 [0.42857143 0.5       ]]
Elementwise power:
[[ 1.  4.]
 [ 9. 16.]]


##### Broadcasting

详细内容请参见 [Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) ([中文版](https://www.numpy.org.cn/user/basics/broadcasting.html))

在 NumPy 的数组运算中，通常要求参与运算的两个数组的形状相同，但在满足某些要求的情况下，NumPy 可以自动地将较小的数组进行复制，使得其与较大的数组形状相同。举例如下：

In [47]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)  # 标量广播为数组

x = np.arange(8).reshape((2, 2, 2))
y = np.array([[10, 20], [30, 40]])
print(x)
print(x + y)  # 小数组广播为大数组

m = np.random.randn(8, 1, 6, 1)
n = np.random.randn(7, 1, 5)
print(m.shape)
print(n.shape)
print((m + n).shape)  # 一般广播规则：维度从后往前匹配，维度兼容的条件：相等或其中1个是1

k = np.random.randn(8, 1, 6, 6)
l = np.random.randn(7, 1, 6)
print(k+l,"\n")
print((k+l).shape)  # 不满足一般广播规则，在最后一维失配

[2. 4. 6.]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[10 21]
  [32 43]]

 [[14 25]
  [36 47]]]
(8, 1, 6, 1)
(7, 1, 5)
(8, 7, 6, 5)
[[[[-7.13461335e-01 -1.40043282e+00 -7.25034125e-01  1.62175773e+00
    -1.94011179e+00  2.93247975e-01]
   [-2.27834986e+00 -1.32483323e+00  3.46881251e-01  1.13809350e+00
    -3.87682103e-01  1.05033464e+00]
   [-1.30497838e+00 -7.85399737e-01 -2.43825852e+00  8.52379109e-01
    -7.95825178e-01 -7.30888665e-01]
   [-1.55700028e+00  1.64125444e+00  2.07966552e-01  1.36292547e+00
    -2.68121942e+00  8.49208460e-01]
   [-1.47708351e-01 -1.30991896e+00 -4.76041127e-01  1.61165753e+00
    -1.39287767e+00 -1.10761012e+00]
   [-2.22774816e-01 -7.11804250e-02  5.30796261e-01  1.05737799e+00
    -4.58710040e-01  3.09675896e-01]]

  [[ 9.41813766e-01 -1.07930482e+00 -1.20569382e+00  8.21328662e-01
    -1.21933382e+00 -1.62768883e-01]
   [-6.23074759e-01 -1.00370523e+00 -1.33778447e-01  3.37664435e-01
     3.33095860e-01  5.94317781e-01]
   [ 3.50296720e-01 -4.64271735

### 4.2 常用数学函数

NumPy 中预置了很多数学函数，大家可以自己探索用法。完整的数学函数列表见 [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html) 和 [Statistics](https://numpy.org/doc/stable/reference/routines.statistics.html)。

#### 4.2.1 单点运算

NumPy 中预置了例如求绝对值、（反）三角函数、（反）双曲函数、指数、对数、取整、截断等常用函数，这些函数也都是逐元素运算的。下面是一些示例：

In [48]:
angle = np.array([0, np.pi / 4, np.pi / 2, np.pi * 3 / 4])
print(np.sin(angle))

power = np.array([0, 1, 2, 3])
result = np.exp(power)
print(result)
print(np.log(result))

[0.         0.70710678 1.         0.70710678]
[ 1.          2.71828183  7.3890561  20.08553692]
[0. 1. 2. 3.]


#### 4.2.2 统计量

NumPy 中预置了求平均值、中位数、方差、标准差，求和、求积，求最大、最小值的函数，很多函数可以通过 `axis` 参数指定沿某一个轴求值（不指定就是对所有元素），还可指定通过 `keepdims` 参数指定求值操作是否要保留原数组的形状。一些常用的函数如下：
- [`sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html): 求和。
- [`prod`](https://numpy.org/doc/stable/reference/generated/numpy.prod.html): 求积。
- [`mean`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html): 求均值。
- [`std`](https://numpy.org/doc/stable/reference/generated/numpy.std.html): 求标准差。
- [`var`](https://numpy.org/doc/stable/reference/generated/numpy.var.html): 求方差。
- [`amax`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html): 求最大值。也可以通过 `max` 调用。
- [`amin`](https://numpy.org/doc/stable/reference/generated/numpy.amin.html): 求最小值。也可以通过 `min` 调用。

例如：

In [49]:
arr = np.random.random((2, 2))
print(arr)
print(np.mean(arr))  # 或 `arr.mean()`。求所有元素的平均值。
print(arr.mean(axis=0))  # 或 `np.mean(arr, axis=0)`。对第 0 维求平均值。
print(np.min(arr))  # 或 `arr.min()`, `np.amin(arr)`。求所有元素的最小值。
print(arr.max(axis=1, keepdims=True))  # 对第 1 维求最大值，保留维度。

[[0.15452196 0.6329802 ]
 [0.52389797 0.14241565]]
0.36345394601499525
[0.33920997 0.38769793]
0.14241565157733171
[[0.6329802 ]
 [0.52389797]]


注意此处不要和 [`maximum`](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html), [`minimum`](https://numpy.org/doc/stable/reference/generated/numpy.minimum.html) 两个函数混淆。这两个函数是对于2个数组，返回逐元素求最大/小值的结果。

In [50]:
print(np.maximum([2, 3, 4], [1, 5, 2]))
print(np.maximum(np.eye(2), [0.5, 2]))

[2 5 4]
[[1.  2. ]
 [0.5 2. ]]


### 4.3 向量、矩阵运算

前面提到，数组的 `*` 运算为逐元素相乘，并不是矩阵乘法。对于矩阵乘法，应当使用 `@` 运算符，或者 [`matmul`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) 函数。当两个数组都是二维时，也可以使用 [`dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)。

In [51]:
x = np.array([[1,2],[3,4]], dtype=np.float32)
y = np.array([[5,6],[7,8]], dtype=np.float32)
x @ y  # equivalent to `np.matmul(x, y)`

array([[19., 22.],
       [43., 50.]], dtype=float32)

使用 [`inner(x, y)`](https://numpy.org/doc/stable/reference/generated/numpy.inner.html) 或 [`dot(x, y)`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) 或 `x.dot(y)` 进行向量点乘。

In [2]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y))  # 或 x.dot(y)

32


使用 [`cross(x, y)`](https://numpy.org/doc/stable/reference/generated/numpy.cross.html) 进行向量叉乘。

In [3]:
print(np.cross(x, y))

[-3  6 -3]


使用 [`linalg.norm(x[, ord, axis, keepdims)`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) 求向量或矩阵的模。

In [53]:
x = np.array([1, 1])
print(np.linalg.norm(x))  # 求向量 x 的模长
y = np.array([[1, 2], [3, 4]])
print(np.linalg.norm(y, axis=1))  # 求 y 的每一行的模长

1.4142135623730951
[2.23606798 5.        ]


使用 [linalg.inv](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html) 求矩阵的逆。

In [60]:
x = np.array([[1,2],[3,4]], dtype=np.float32)
y = np.linalg.inv(x)
print(y)
print(np.matmul(x, y))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


### 4.4 排序与查找

更详细的内容，请参考 [Sorting, searching, and counting](https://numpy.org/doc/stable/reference/routines.sort.html)。

#### 4.4.1 排序

排序常用的函数是：
- [`sort(a, axis=-1)`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html): 沿着给定的 `axis` 从小到大排序元素。如果 `axis` 为 `None`，则会先把数组展平为一维，然后再对所有元素进行排序。该函数返回的是一个新数组，而如果使用 [`ndarray.sort`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html)，则会在原地进行排序，不返回值。
- [`argsort(a, axis=-1)`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html): 按照与 `sort` 相同的规则排序元素，返回排序后的元素在原数组的排序维度上的索引。

In [74]:
x = np.array([[0, 3], [4, 2]])
y = x.copy()
print("排序前x的值\n",x)
print("x沿最后一维排序\n", np.sort(x))  # 沿最后一维进行排序
print("排序后x的值\n",x)  # np.sort返回新数组，对原本x无影响
y.sort() # 沿最后一位进行排序，对原本y有影响
print("y沿最后一位排序\n",y)  
print(np.sort(x, axis=0))  # 沿第 0 维进行排序
print(np.sort(x, axis=None))  # 对所有元素进行排序



排序前x的值
 [[0 3]
 [4 2]]
x沿最后一维排序
 [[0 3]
 [2 4]]
排序后x的值
 [[0 3]
 [4 2]]
y沿最后一位排序
 [[0 3]
 [2 4]]
[[0 2]
 [4 3]]
[0 2 3 4]


In [75]:
print(x)
print(np.argsort(x))  # 沿最后一维进行排序
print(np.argsort(x, axis=0))  # 沿第 0 维进行排序

[[0 3]
 [4 2]]
[[0 1]
 [1 0]]
[[0 1]
 [1 0]]


如何根据 `argsort` 返回的索引从原数组提取元素呢？需要用到 [`take_along_axis(arr, indices, axis)`](https://numpy.org/doc/stable/reference/generated/numpy.take_along_axis.html)。

In [76]:
print(np.take_along_axis(x, np.argsort(x, axis=0), axis=0))

[[0 2]
 [4 3]]


In [80]:
print(np.argsort(x, axis=None))  # 对所有元素进行排序

[0 3 1 2]


我们发现，对所有元素进行排序返回的索引是一个一维数组，这是因为原数组在排序时被展平为了一个一维数组。那么如何根据这个索引得到元素在原数组中的多维的索引呢？这里需要用到 [`unravel_index(indices, shape)`](https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html) 函数。输入一维索引数组和原数组的形状，该函数会将一维索引转换为多维索引。

In [81]:
print(np.unravel_index(np.argsort(x, axis=None), x.shape))

(array([0, 1, 0, 1], dtype=int64), array([0, 1, 1, 0], dtype=int64))


可以看到，函数返回了两个一维数组，分别对应原数组两个维度上的索引。

#### 4.4.2 查找

常用的查找函数包括：
- [`argmax(a, axis=None)`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html): 沿 `axis` 轴找出取值最大的元素的索引。若不指定 `axis`，则会先将数组展平到一维，然后再进行查找。
- [`argmin(a, axis=None])`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html): 沿 `axis` 轴找出取值最小的元素的索引。若不指定 `axis`，则会先将数组展平到一维，然后再进行查找。

与 `argsort` 一样，这里有时也会用到 `unravel_index` 和 `take_along_axis`。

In [5]:
import numpy as np
x = np.array([[0, 5, 3], [4, 5, 2]])
a = np.argmin(x, axis=0)
print(a)
min_values = x[a, range(x.shape[1])]  # 沿第 0 维找最小值, range(x.shape[1]) 相当于 [0, 1, 2]
# [a,[0,1,2]]给出了最小值的位置  这个和上面的argsort比较相似
print(min_values)

[0 0 1]
[0 5 2]


- [`argwhere(a)`](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html): 返回数组中非零元素的索引构成的数组。数组的形状为 `(N, a.ndim)`，`N` 为查找到元素的个数。注：`True` 也是非零元素，因此我们可以传入通过条件比较得到的布尔数组来筛选出满足条件的元素。
- [`nonzero(a)`](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html): 对数组中的非零元素，分别返回每一维的索引构成的数组。因为 `argwhere` 返回的索引数组不适合用于从原数组提取元素，所以有时会用 `nonzero` 替代。

In [8]:
print(np.argwhere(x > 3))
ind_0, ind_1 = np.nonzero(x > 3)
print(ind_0, ind_1)

y =[[False,False],[False,False]]
ind_01,ind_11 = np.nonzero(y)
print(ind_01,ind_11)

[[0 1]
 [1 0]
 [1 1]]
[0 1 1] [1 0 1]
[] []


In [84]:
print(x[ind_0, ind_1])
print(x[x > 3])  # 其实用布尔数组索引就行了

[5 4 6]
[5 4 6]


## 5. 数组的操作

详细文档请参见 [Array manipulation routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)。

### 5.1 改变数组形状

- [`reshape(a, shape)`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) / [`ndarray.reshape(shape)`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html): 改变数组的形状为 `shape`。`shape` 里的某一维的大小可以设置为 `-1`，此时将根据数组元素个数和其他维度大小自动推断该维度的大小。
- [`ravel(a)`](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html) / [`ndarray.ravel()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ravel.html): 将数组展平为一维。返回的是原数组的 view。
- [`ndarray.flatten()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html): 将数组展平为一维。返回的是新的数组。

In [9]:
arr = np.arange(6)
print(arr)
print(arr.reshape((2, 3)))
print(np.reshape(arr, (-1, 2)))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [10]:
arr = np.zeros((2, 2))
print(arr)
print(np.ravel(arr))  # 或 arr.flatten()

[[0. 0.]
 [0. 0.]]
[0. 0. 0. 0.]


- [`squeeze(a, axis=None)`](https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html) / [`ndarray.squeeze(axis=None)`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.squeeze.html): 删除数组中大小为 1 的维度。如果指定了 `axis`，就只删除该维度。
- [`expand_dims(a, axis)`](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html): 向 `axis` 处插入一个维度。

In [13]:
x = np.array([[1], [2]])
print(x, x.shape)
y = x.squeeze(1)
print("\n",y, y.shape)
z = np.expand_dims(x, axis=0)
print("\n",z, z.shape)

[[1]
 [2]] (2, 1)

 [1 2] (2,)

 [[[1]
  [2]]] (1, 2, 1)


还可以利用特殊的索引值 `np.newaxis` (也可以写 `None`) 来扩展维度。例如：

In [17]:
print(y, y.shape)
print(y[np.newaxis], y[np.newaxis].shape)  # 扩展第0维
print(y[:,np.newaxis],y[:,np.newaxis].shape)  # 扩展第1维
print(y[..., np.newaxis], y[..., np.newaxis].shape)  # 扩展最后一维。`...` 表示之前的所有维度。

[1 2] (2,)
[[1 2]] (1, 2)
[[1]
 [2]] (2, 1)
[[1]
 [2]] (2, 1)


In [22]:
import numpy as np  
  
# 创建一个 2x2x2 的三维数组  
x = np.arange(8).reshape(2, 2, 2)  
print("原始数组 x:")  
print(x)  
  
# 在数组的开头添加新的维度，使用 np.newaxis 或 None（它们是等价的）  
#x_expanded = x[np.newaxis, :, :, :]  
# 或者  
x_expanded = x[:, :, :, np.newaxis]  
print("扩展后的数组 x_expanded:")  
print(x_expanded)  
print("扩展后的数组形状:", x_expanded.shape)
print(x[:,np.newaxis,:,:].shape)

原始数组 x:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
扩展后的数组 x_expanded:
[[[[0]
   [1]]

  [[2]
   [3]]]


 [[[4]
   [5]]

  [[6]
   [7]]]]
扩展后的数组形状: (2, 2, 2, 1)
(2, 1, 2, 2)


### 5.2 转置
- [`transpose(a, axes=None)`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) / [`ndarray.transpose(axes=None)`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html): 按照 `axes` 指定的维度顺序转置数组。若未指定 `axes`，则反转所有维度的顺序。
- [`ndarray.T`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html): 等同于 `ndarray.transpose()`。

In [23]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(np.transpose(x))
print(x.T)
print(x)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]


In [93]:
x = np.arange(6).reshape((1, 2, 3))
print(x, x.shape)
y = x.transpose((1, 2, 0))
print(y, y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


### 5.3 改变数据类型

- [`ndarray.astype(dtype)`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html): 复制并转换数组到指定的数据类型。

In [94]:
img = np.random.random((2, 2))  # 像素值取值 0~1 的图像
print(img)
img = (img * 255).round().astype(np.uint8)  # 转换为常见的 uint8 图像
print(img)

[[0.91401126 0.42424438]
 [0.02389619 0.41669336]]
[[233 108]
 [  6 106]]


### 5.4 数组的拼接与堆叠

- [`concatenate(arrays, axis=0)`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html): 在**已有**的维度上，拼接多个数组。若 `axis` 为 `None`，则会先将所有待拼接数组转换为一维数组，再进行拼接。
- [`stack(arrays, axis=0)`](https://numpy.org/doc/stable/reference/generated/numpy.stack.html): 沿着**新的维度**堆叠多个数组。

In [26]:
img_a = np.array([[1, 2], [3, 4]])
img_b = np.array([[5, 6], [7, 8]])
print(np.concatenate([img_a, img_b], axis=0))
print(np.concatenate([img_a, img_b], axis=1))

img_c = np.arange(10).reshape((2, 5))
print(np.concatenate([img_a, img_c], axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 0 1 2 3 4]
 [3 4 5 6 7 8 9]]


In [25]:
img_stack_channel = np.stack([img_a, img_b], axis=2)
print(img_stack_channel, img_stack_channel.shape)
img_stack_batch = np.stack([img_a, img_b], axis=0)
print(img_stack_batch, img_stack_batch.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]] (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


- [`tile(arr, reps)`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html): 将 `arr` 按照 `reps` 指定的维度和次数进行堆叠。

In [97]:
arr = np.array([0, 1, 2])
print(np.tile(arr, 2))
print(np.tile(arr, (2, 2)))

[0 1 2 0 1 2]
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


## 6. 数组的文件 I/O

完整文档请参见 [Input and output](https://numpy.org/doc/stable/reference/routines.io.html)。

有时，我们需要将某个数组保存到文件，或是从文件中读取数组。通常使用如下函数：
- [`load(file)`](https://numpy.org/doc/stable/reference/generated/numpy.load.html): 从 `.npy` 或 `.npz` 文件读取数组。
- [`save(file, arr)`](https://numpy.org/doc/stable/reference/generated/numpy.save.html): 保存单个数组到 `.npy` 文件。
- [`savez(file, key0=arr0[, key1=arr1])`](https://numpy.org/doc/stable/reference/generated/numpy.savez.html): 保存多个数组到 `.npz` 文件。
- [`savez_compressed(file, key0=arr0[, key1=arr1])`](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html): 同 `savez`，但会进行压缩处理。

示例如下：

In [27]:
x = np.random.random((2, 2))
print(x)
np.save('x.npy', x)

x_loaded = np.load('x.npy')
print(x_loaded)

[[0.03625511 0.07257783]
 [0.52999696 0.3950703 ]]
[[0.03625511 0.07257783]
 [0.52999696 0.3950703 ]]


In [29]:
y = np.random.random((2, 2))
print(y)
np.savez('arrays.npz', x=x, y=y)

data = np.load('arrays.npz')
x_loaded, y_loaded = data['x'], data['y']
print(x_loaded)
print(y_loaded)

[[0.47514212 0.82084867]
 [0.74552182 0.64836562]]
[[0.03625511 0.07257783]
 [0.52999696 0.3950703 ]]
[[0.47514212 0.82084867]
 [0.74552182 0.64836562]]
